# Generated by Django 3.2.12 on 2022-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
