# Generated by Django 4.0.2 on 2022-02-11 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 18, 53, 49, 117931, tzinfo=utc), editable=False),
        ),
    ]
