# Generated by Django 4.0.2 on 2022-02-11 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 18, 55, 40, 197877, tzinfo=utc), editable=False),
        ),
    ]
